OPSymbol: '*'
CreativeSymbol: '~'
SurvivalSymbol: '!'
ShowBothStatus: false
TooLongTabNameSymbol: '..'
ShowInTAB: true
TabFormat: '$HIDDEN$OP$CREATIVE$LASTCOLORPREFIX$NAME'
ShowInDisplayName: true
DisplayNameFormat: '$LASTCOLORPREFIX$NAME'
ShowInOverhead: true
OverheadFormat: '$LASTCOLORPREFIX$NAME'
ColorNamesInChat: true
VanishedSymbol: '?'