name: iChatPlayerList
main: com.worldcretornica.ichatplayerlist.iChatPlayerList
version: '0.10'
softdepend: [iChat, PermissionsEX, TagAPI, SupaChat, VanishNoPacket]
description: >
             Using iChat, SupaChat or PEX, color the player displayname and playerlist name
commands:
    ichatplayerlist:
        description: Reloads ichat configuration
        usage: /ichatplayerlist reload